from enum import Enum


class MapEvent(Enum):
    UPDATE_POSITION_ON_MAP = "UPDATE_POSITION_ON_MAP"
    REMOVE_FROM_MAP = "REMOVE_FROM_MAP"
    MAP_COMPLETED = "MAP_COMPLETED"
    MAP_UNCOMPLETED = "MAP_UNCOMPLETED"
